spring:
  datasource:
    url: jdbc:mysql://localhost:3306/asb
    username: root
    password: root

  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
    generate-ddl: true
    open-in-view: false

cors:
  front-end: ${CORS_FRONT_END:http://localhost:5173}

server:
  error:
    include-stacktrace: never